-- AlterTable
ALTER TABLE "pets" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ALIVE';
ALTER TABLE "pets" ADD COLUMN IF NOT EXISTS "statusReason" TEXT;
ALTER TABLE "pets" ADD COLUMN IF NOT EXISTS "statusDate" TIMESTAMP(3);
